// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVJF3qdc7LtG_zYQHzPmKVhtsVdd_ljk',
    appId: '1:969321273114:android:7949fdccb127a305a7fea3',
    messagingSenderId: '969321273114',
    projectId: 'health-device-b7f95',
    databaseURL: 'https://health-device-b7f95-default-rtdb.firebaseio.com',
    storageBucket: 'health-device-b7f95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFCx_XXSCckm9c7BrMif95WP_TCxHfFU',
    appId: '1:969321273114:ios:332c34c69fa7475aa7fea3',
    messagingSenderId: '969321273114',
    projectId: 'health-device-b7f95',
    databaseURL: 'https://health-device-b7f95-default-rtdb.firebaseio.com',
    storageBucket: 'health-device-b7f95.appspot.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHeQNe83OWxFY9ja-rCLFRyiKxZqKujqs',
    appId: '1:969321273114:web:d2106ff8afbb27eea7fea3',
    messagingSenderId: '969321273114',
    projectId: 'health-device-b7f95',
    authDomain: 'health-device-b7f95.firebaseapp.com',
    databaseURL: 'https://health-device-b7f95-default-rtdb.firebaseio.com',
    storageBucket: 'health-device-b7f95.appspot.com',
    measurementId: 'G-72ELM9P2KB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFCx_XXSCckm9c7BrMif95WP_TCxHfFU',
    appId: '1:969321273114:ios:332c34c69fa7475aa7fea3',
    messagingSenderId: '969321273114',
    projectId: 'health-device-b7f95',
    databaseURL: 'https://health-device-b7f95-default-rtdb.firebaseio.com',
    storageBucket: 'health-device-b7f95.appspot.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHeQNe83OWxFY9ja-rCLFRyiKxZqKujqs',
    appId: '1:969321273114:web:4d2068348ae5d277a7fea3',
    messagingSenderId: '969321273114',
    projectId: 'health-device-b7f95',
    authDomain: 'health-device-b7f95.firebaseapp.com',
    databaseURL: 'https://health-device-b7f95-default-rtdb.firebaseio.com',
    storageBucket: 'health-device-b7f95.appspot.com',
    measurementId: 'G-GF3QHMLCLY',
  );

}